import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
// import { getSiteSettings } from "@/Hooks/api/cms_api"; 
import AosProvider from "@/Provider/AosProvider/AosProvider";
import AuthProvider from "@/Provider/AuthProvider/AuthProvider";
import QueryProvider from "@/Provider/QueryProvider/QueryProvider";

// Fonts
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  display: "swap",
});

// Metadata
export const metadata: Metadata = {
  title: "TalentHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const faviconUrl = "/favicon.svg";

  return (
    <html lang="en">
      <head>
        <link rel="icon" href={faviconUrl} />
      </head>

      <body
        suppressHydrationWarning
        className={`${inter.variable} antialiased`}
      >
        <QueryProvider>
          <AuthProvider>
            <AosProvider>
              <Toaster />
              {children}
            </AosProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
